//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Ver1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingDetail
    {
        public string CopyID { get; set; }
        public int BorrowID { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool Status { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
        public virtual Borrowing Borrowing { get; set; }
    }
}
