//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Ver1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borrowing()
        {
            this.BorrowingDetails = new HashSet<BorrowingDetail>();
        }
    
        public int BorrowID { get; set; }
        public string BorrowCode { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Email { get; set; }
        public string UpdatedEmail { get; set; }
        public bool Type { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowingDetail> BorrowingDetails { get; set; }
    }
}
